export interface CalibrationItem {
  no: number
  equipment_id: string
  equipment_name: string
  owner: string
  owner_name: string
  brand: string
  model: string
  serial_number: string
  operation_range: string
  calibration_range: string
  acceptance_criteria: string
  interval_months: number
  cal_type: string
  cal_provider: string
  status_note: string
  scheduled_month: string
}

export const CALIBRATION_ITEMS: CalibrationItem[] = [
  {
    "no": 1,
    "equipment_id": "BAL-PK-001",
    "equipment_name": "Balance (0.1 g) / (Cap.3,000 g)",
    "owner": "PK",
    "owner_name": "แผนกบรรจุและแพ็กกิ้ง (Packing)",
    "brand": "OHAUS",
    "model": "V11P3",
    "serial_number": "50930420",
    "operation_range": "0-3000 g",
    "calibration_range": "0-3000 g",
    "acceptance_criteria": "±0.3 g",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 2,
    "equipment_id": "BAL-PK-003",
    "equipment_name": "Balance (0.1 g) / (Cap.3,000 g)",
    "owner": "PK",
    "owner_name": "แผนกบรรจุและแพ็กกิ้ง (Packing)",
    "brand": "OHAUS",
    "model": "V11P3",
    "serial_number": "50930424",
    "operation_range": "0-3000 g",
    "calibration_range": "0-3000 g",
    "acceptance_criteria": "±0.3 g",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 3,
    "equipment_id": "BAL-PK-006",
    "equipment_name": "Balance (0.1 g) / (Cap.3,000 g)",
    "owner": "PK",
    "owner_name": "แผนกบรรจุและแพ็กกิ้ง (Packing)",
    "brand": "OHAUS",
    "model": "V11P3",
    "serial_number": "50930429",
    "operation_range": "0-3000 g",
    "calibration_range": "0-3000 g",
    "acceptance_criteria": "±0.3 g",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 4,
    "equipment_id": "BAL-PK-010",
    "equipment_name": "Balance (0.1 g) / (Cap.3,000 g)",
    "owner": "PK",
    "owner_name": "แผนกบรรจุและแพ็กกิ้ง (Packing)",
    "brand": "OHAUS",
    "model": "V11P3",
    "serial_number": "50930245",
    "operation_range": "0-3000 g",
    "calibration_range": "0-3000 g",
    "acceptance_criteria": "±0.3 g",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 5,
    "equipment_id": "BAL-PK-011",
    "equipment_name": "Balance (0.002 kg) / (Cap.30 Kg)",
    "owner": "PK",
    "owner_name": "แผนกบรรจุและแพ็กกิ้ง (Packing)",
    "brand": "OHAUS",
    "model": "T31P",
    "serial_number": "B553920010",
    "operation_range": "0-30 kg",
    "calibration_range": "0-30 kg",
    "acceptance_criteria": "±0.03 kg",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 6,
    "equipment_id": "BAL-PK-012",
    "equipment_name": "Balance (0.1 g) / (Cap.3,000 g)",
    "owner": "PK",
    "owner_name": "แผนกบรรจุและแพ็กกิ้ง (Packing)",
    "brand": "OHAUS",
    "model": "V11P3",
    "serial_number": "50930426",
    "operation_range": "0-3000 g",
    "calibration_range": "0-3000 g",
    "acceptance_criteria": "±0.3 g",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 7,
    "equipment_id": "BAL-PK-013",
    "equipment_name": "Balance (0.1 g) / (Cap.1,500 g)",
    "owner": "PK",
    "owner_name": "แผนกบรรจุและแพ็กกิ้ง (Packing)",
    "brand": "Concrete",
    "model": "ACS-1,5-078",
    "serial_number": "1117072601602-A",
    "operation_range": "0-1500 g",
    "calibration_range": "0-1500 g",
    "acceptance_criteria": "±0.3 g",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 8,
    "equipment_id": "BAL-PK-014",
    "equipment_name": "Balance (0.1 g) / (Cap 1,500 g)",
    "owner": "PK",
    "owner_name": "แผนกบรรจุและแพ็กกิ้ง (Packing)",
    "brand": "Concrete",
    "model": "ACS-1,5-078",
    "serial_number": "1117072600702-A",
    "operation_range": "0-1500 g",
    "calibration_range": "0-1500 g",
    "acceptance_criteria": "±0.3 g",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 9,
    "equipment_id": "BAL-PK-015",
    "equipment_name": "Balance (0.01 kg) / (Cap 30 Kg)",
    "owner": "PK",
    "owner_name": "แผนกบรรจุและแพ็กกิ้ง (Packing)",
    "brand": "OHAUS",
    "model": "T24PE",
    "serial_number": "B000111JFU",
    "operation_range": "0-30 kg",
    "calibration_range": "0-30 kg",
    "acceptance_criteria": "±0.03 kg",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 10,
    "equipment_id": "BAL-PK-016",
    "equipment_name": "Balance (0.1 g) / (Cap.1,500 g)",
    "owner": "PK",
    "owner_name": "แผนกบรรจุและแพ็กกิ้ง (Packing)",
    "brand": "Concrete",
    "model": "ACS-1,5-078",
    "serial_number": "1119121302302-A",
    "operation_range": "0-1500 g",
    "calibration_range": "0-1500 g",
    "acceptance_criteria": "±0.3 g",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 11,
    "equipment_id": "BAL-PK-017",
    "equipment_name": "Balance (0.1 g) / (Cap.1,500 g)",
    "owner": "PK",
    "owner_name": "แผนกบรรจุและแพ็กกิ้ง (Packing)",
    "brand": "Concrete",
    "model": "ACS-1,5-078",
    "serial_number": "1119121303002-A",
    "operation_range": "0-1500 g",
    "calibration_range": "0-1500 g",
    "acceptance_criteria": "±0.3 g",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 12,
    "equipment_id": "BAL-PK-018",
    "equipment_name": "Balance (0.1 g) / (Cap.1,500 g)",
    "owner": "PK",
    "owner_name": "แผนกบรรจุและแพ็กกิ้ง (Packing)",
    "brand": "Concrete",
    "model": "ACS-1,5-078",
    "serial_number": "1119121302102-A",
    "operation_range": "0-1500 g",
    "calibration_range": "0-1500 g",
    "acceptance_criteria": "±0.3 g",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 13,
    "equipment_id": "HTM-PK-001",
    "equipment_name": "Hygro Thermometer",
    "owner": "PK",
    "owner_name": "แผนกบรรจุและแพ็กกิ้ง (Packing)",
    "brand": "DIGICON",
    "model": "TH-02A",
    "serial_number": "375013924",
    "operation_range": "(-10) - (+50)°C",
    "calibration_range": "25°C,  50 %RH",
    "acceptance_criteria": "±3°C, ±15 %RH",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 14,
    "equipment_id": "HTM-PK-002",
    "equipment_name": "Hygro Thermometer",
    "owner": "PK",
    "owner_name": "แผนกบรรจุและแพ็กกิ้ง (Packing)",
    "brand": "DIGICON",
    "model": "TH-02A",
    "serial_number": "375013922",
    "operation_range": "(-10) - (+50)°C",
    "calibration_range": "25°C,  50 %RH",
    "acceptance_criteria": "±3°C, ±15 %RH",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 15,
    "equipment_id": "HTM-PK-003",
    "equipment_name": "Hygro Thermometer",
    "owner": "PK",
    "owner_name": "แผนกบรรจุและแพ็กกิ้ง (Packing)",
    "brand": "PONPE",
    "model": "PONPE490",
    "serial_number": "PONPE5810073",
    "operation_range": "(-10) - (+50)°C",
    "calibration_range": "25°C,  50 %RH",
    "acceptance_criteria": "±3°C, ±15 %RH",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 16,
    "equipment_id": "STW-PK-001",
    "equipment_name": "Standard Weight 500 g",
    "owner": "PK",
    "owner_name": "แผนกบรรจุและแพ็กกิ้ง (Packing)",
    "brand": "N/A",
    "model": "500g",
    "serial_number": "BRASS/M1",
    "operation_range": "500g",
    "calibration_range": "500g",
    "acceptance_criteria": "± 1 g",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 17,
    "equipment_id": "STW-PK-002",
    "equipment_name": "Standard Weight 500 g",
    "owner": "PK",
    "owner_name": "แผนกบรรจุและแพ็กกิ้ง (Packing)",
    "brand": "N/A",
    "model": "500g",
    "serial_number": "BRASS/M1",
    "operation_range": "500g",
    "calibration_range": "500g",
    "acceptance_criteria": "± 1 g",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 18,
    "equipment_id": "STW-PK-003",
    "equipment_name": "Standard Weight 500 g",
    "owner": "PK",
    "owner_name": "แผนกบรรจุและแพ็กกิ้ง (Packing)",
    "brand": "N/A",
    "model": "500g",
    "serial_number": "BRASS/M1",
    "operation_range": "500g",
    "calibration_range": "500g",
    "acceptance_criteria": "± 1 g",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 19,
    "equipment_id": "STW-PK-004",
    "equipment_name": "Standard Weight 500 g",
    "owner": "PK",
    "owner_name": "แผนกบรรจุและแพ็กกิ้ง (Packing)",
    "brand": "N/A",
    "model": "500g",
    "serial_number": "BRASS/M1",
    "operation_range": "500g",
    "calibration_range": "500g",
    "acceptance_criteria": "± 1 g",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 20,
    "equipment_id": "HTM-PD-007",
    "equipment_name": "Digital Thermo Hygrometer",
    "owner": "MX",
    "owner_name": "แผนกผสม (Mixing)",
    "brand": "DIGICON",
    "model": "TH-02",
    "serial_number": "355081466",
    "operation_range": "(-10) - (+50)°C",
    "calibration_range": "25°C,  50 %RH",
    "acceptance_criteria": "±3°C, ±15 %RH",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 21,
    "equipment_id": "BAL-RD-001",
    "equipment_name": "Balance (0.01 g) / ( Cap.5,000 g)",
    "owner": "RD",
    "owner_name": "ฝ่ายวิจัยและพัฒนา (R&D)",
    "brand": "Njbonitalab",
    "model": "DNC5002",
    "serial_number": "2217300121",
    "operation_range": "0-5000 g",
    "calibration_range": "0-5000 g",
    "acceptance_criteria": "±0.03 g",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "Cal 16/02/24",
    "scheduled_month": "FEB"
  },
  {
    "no": 22,
    "equipment_id": "BAL-RD-002",
    "equipment_name": "Balance (0.01 g) / (Cap.5,000 g)",
    "owner": "RD",
    "owner_name": "ฝ่ายวิจัยและพัฒนา (R&D)",
    "brand": "Nibonitalab",
    "model": "DNC5002",
    "serial_number": "2217300314",
    "operation_range": "0-5000 g",
    "calibration_range": "0-5000 g",
    "acceptance_criteria": "±0.03 g",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 23,
    "equipment_id": "HTM-RD-001",
    "equipment_name": "Hygro Thermometer",
    "owner": "RD",
    "owner_name": "ฝ่ายวิจัยและพัฒนา (R&D)",
    "brand": "Ponpe",
    "model": "PONPE 490",
    "serial_number": "PONPE5814422",
    "operation_range": "(-10) - (+50)°C",
    "calibration_range": "25°C,  50 %RH",
    "acceptance_criteria": "±3°C, ±15 %RH",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "Cal 16/02/24",
    "scheduled_month": "FEB"
  },
  {
    "no": 24,
    "equipment_id": "INC-RD-001",
    "equipment_name": "Incubator",
    "owner": "RD",
    "owner_name": "ฝ่ายวิจัยและพัฒนา (R&D)",
    "brand": "Memmert",
    "model": "IN110",
    "serial_number": "D420.0322",
    "operation_range": "45°C",
    "calibration_range": "45°C",
    "acceptance_criteria": "±2°C",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 25,
    "equipment_id": "LIG-RD-001",
    "equipment_name": "Liquid in glass Thermometer",
    "owner": "RD",
    "owner_name": "ฝ่ายวิจัยและพัฒนา (R&D)",
    "brand": "-",
    "model": "-",
    "serial_number": "-",
    "operation_range": "75°C",
    "calibration_range": "75°C",
    "acceptance_criteria": "±1°C",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 26,
    "equipment_id": "LIG-RD-003",
    "equipment_name": "Liquid in glass Thermometer",
    "owner": "RD",
    "owner_name": "ฝ่ายวิจัยและพัฒนา (R&D)",
    "brand": "-",
    "model": "-",
    "serial_number": "-",
    "operation_range": "75°C",
    "calibration_range": "75°C",
    "acceptance_criteria": "±1°C",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 27,
    "equipment_id": "STW-RD-001",
    "equipment_name": "Standard Weight 100 g",
    "owner": "RD",
    "owner_name": "ฝ่ายวิจัยและพัฒนา (R&D)",
    "brand": "-",
    "model": "100 g",
    "serial_number": "-",
    "operation_range": "100 g",
    "calibration_range": "100 g",
    "acceptance_criteria": "±  1 mg",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 28,
    "equipment_id": "STW-MM-008",
    "equipment_name": "Standard Weight 50 g",
    "owner": "MM",
    "owner_name": "คลังวัตถุดิบและบรรจุภัณฑ์ (Warehouse/RM)",
    "brand": "N/A",
    "model": "50g",
    "serial_number": "-",
    "operation_range": "50g",
    "calibration_range": "50g",
    "acceptance_criteria": "±  1 mg",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "18/06/24 อยู่ในห้อง RD",
    "scheduled_month": "JUN"
  },
  {
    "no": 29,
    "equipment_id": "BAL-RD-004",
    "equipment_name": "Balance (0.01 g) / (Cap.5,000 g)",
    "owner": "RD",
    "owner_name": "ฝ่ายวิจัยและพัฒนา (R&D)",
    "brand": "TOMS",
    "model": "TM-EXC50002",
    "serial_number": "231003923",
    "operation_range": "0-1000 g",
    "calibration_range": "0-5000 g",
    "acceptance_criteria": "±0.03 g",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "Cal 25/03/24",
    "scheduled_month": "MAR"
  },
  {
    "no": 30,
    "equipment_id": "BAL-RD-005",
    "equipment_name": "Balance (0.001 g) / (Cap.410g)",
    "owner": "MM",
    "owner_name": "คลังวัตถุดิบและบรรจุภัณฑ์ (Warehouse/RM)",
    "brand": "OHAUS",
    "model": "PA413",
    "serial_number": "B609161159",
    "operation_range": "0-410 g",
    "calibration_range": "0-410 g",
    "acceptance_criteria": "±0.003 g",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "20/06/24  มีการโอนย้ายเปลี่ยนรหัส จาก BAL- MM-001 เป็น BAL-RD-005",
    "scheduled_month": "JUN"
  },
  {
    "no": 31,
    "equipment_id": "BAL-RD-003",
    "equipment_name": "Balance (0.0001 g)",
    "owner": "RD",
    "owner_name": "ฝ่ายวิจัยและพัฒนา (R&D)",
    "brand": "OHAUS",
    "model": "Pioneer/ PA214",
    "serial_number": "B5444636439",
    "operation_range": "0-210 g",
    "calibration_range": "0-210 g",
    "acceptance_criteria": "±0.005 g",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "29/01/25 นำกลับเข้ามาให้ Cal อีกครั้ง",
    "scheduled_month": "JAN"
  },
  {
    "no": 32,
    "equipment_id": "HTM-MX-001",
    "equipment_name": "Digital Thermo Hygrometer",
    "owner": "MX",
    "owner_name": "แผนกผสม (Mixing)",
    "brand": "SMART-SENSOR",
    "model": "AR867",
    "serial_number": "-",
    "operation_range": "(-10) - (+50)°C",
    "calibration_range": "25°C,  50 %RH",
    "acceptance_criteria": "±3°C, ±15 %RH",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "Cal 19/02/24",
    "scheduled_month": "FEB"
  },
  {
    "no": 33,
    "equipment_id": "HTM-MX-002",
    "equipment_name": "Digital Thermo Hygrometer",
    "owner": "MX",
    "owner_name": "แผนกผสม (Mixing)",
    "brand": "SMART-SENSOR",
    "model": "AR867",
    "serial_number": "-",
    "operation_range": "(-10) - (+50)°C",
    "calibration_range": "25°C,  50 %RH",
    "acceptance_criteria": "±3°C, ±15 %RH",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "Cal 19/02/24",
    "scheduled_month": "FEB"
  },
  {
    "no": 34,
    "equipment_id": "TCP-MX-001",
    "equipment_name": "Digital Thermometer แบบเข็มยาว 20 cm.",
    "owner": "MX",
    "owner_name": "แผนกผสม (Mixing)",
    "brand": "PONPE",
    "model": "PONPE421TK",
    "serial_number": "PONPE5814423",
    "operation_range": "0-100°C",
    "calibration_range": "25,50,65,95°C",
    "acceptance_criteria": "+/-1°C",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 35,
    "equipment_id": "DTM-MX-001",
    "equipment_name": "Digital Thermometer with probe",
    "owner": "MX",
    "owner_name": "แผนกผสม (Mixing)",
    "brand": "-",
    "model": "TP101",
    "serial_number": "PONPE5868441",
    "operation_range": "(-10) - (+100)°C",
    "calibration_range": "25,50,65,95°C",
    "acceptance_criteria": "+/-1°C",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 36,
    "equipment_id": "DTM-MX-002",
    "equipment_name": "Digital Thermometer (0.1 0C)",
    "owner": "MX",
    "owner_name": "แผนกผสม (Mixing)",
    "brand": "JEDTO",
    "model": "TP3001",
    "serial_number": "PONPE5877147",
    "operation_range": "0-100°C",
    "calibration_range": "25,50,65,95°C",
    "acceptance_criteria": "+/-1°C",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 37,
    "equipment_id": "DTM-MX-003",
    "equipment_name": "Digital Thermometer (0.1 0C)",
    "owner": "MX",
    "owner_name": "แผนกผสม (Mixing)",
    "brand": "JEDTO",
    "model": "TP3001",
    "serial_number": "PONPE5877146",
    "operation_range": "0-100°C",
    "calibration_range": "25,50,65,95°C",
    "acceptance_criteria": "+/-1°C",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 38,
    "equipment_id": "BAL-MX-001",
    "equipment_name": "Balance (0.02 Kg) / (Cap.300 Kg)",
    "owner": "MX",
    "owner_name": "แผนกผสม (Mixing)",
    "brand": "JADEVER",
    "model": "JWI-310",
    "serial_number": "160611134627",
    "operation_range": "0-300 kg",
    "calibration_range": "0-300 kg",
    "acceptance_criteria": "±0.3 kg",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 39,
    "equipment_id": "BAL-MX-002",
    "equipment_name": "Balance (0.1 Kg) / (Cap.1,000 Kg)",
    "owner": "MX",
    "owner_name": "แผนกผสม (Mixing)",
    "brand": "OHAUS",
    "model": "T31P",
    "serial_number": "B522003943",
    "operation_range": "0-1000 kg",
    "calibration_range": "0-1000 kg",
    "acceptance_criteria": "±0.3 kg",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "BAL-MM-003 เปลึ่ยนไปเป็นของ MX-002 แทน",
    "scheduled_month": "FEB"
  },
  {
    "no": 40,
    "equipment_id": "BAL-MX-003",
    "equipment_name": "Balance (0.02 Kg) / (Cap.300 Kg)",
    "owner": "MX",
    "owner_name": "แผนกผสม (Mixing)",
    "brand": "JADEVER",
    "model": "JWI-3100",
    "serial_number": "210620115N1761",
    "operation_range": "0-300 Kg",
    "calibration_range": "0-300 kg",
    "acceptance_criteria": "±0.3 kg",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 41,
    "equipment_id": "DTM-MX-004",
    "equipment_name": "Digital Thermometer (0.1 0C)",
    "owner": "MX",
    "owner_name": "แผนกผสม (Mixing)",
    "brand": "JEDTO",
    "model": "TP3001",
    "serial_number": "PONPE5879447",
    "operation_range": "0-100°C",
    "calibration_range": "25,50,65,95°C",
    "acceptance_criteria": "+/-1°C",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "Cal 16/02/24",
    "scheduled_month": "FEB"
  },
  {
    "no": 42,
    "equipment_id": "DTM-MX-005",
    "equipment_name": "Digital Thermometer (0.1 0C)",
    "owner": "MX",
    "owner_name": "แผนกผสม (Mixing)",
    "brand": "JEDTO",
    "model": "TP3001",
    "serial_number": "PONPE5879446",
    "operation_range": "0-100°C",
    "calibration_range": "25,50,65,95°C",
    "acceptance_criteria": "+/-1°C",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "Cal 16/02/24",
    "scheduled_month": "FEB"
  },
  {
    "no": 43,
    "equipment_id": "PHM-QC-001",
    "equipment_name": "pH meter",
    "owner": "QC",
    "owner_name": "ฝ่ายควบคุมคุณภาพ (Quality Control)",
    "brand": "OHAUS",
    "model": "Starter3100/ ST3100",
    "serial_number": "B609174051",
    "operation_range": "pH 0-14",
    "calibration_range": "4, 7, 10",
    "acceptance_criteria": "±0.3pH",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 44,
    "equipment_id": "CDM-QC-001",
    "equipment_name": "Conductivity Meter",
    "owner": "QC",
    "owner_name": "ฝ่ายควบคุมคุณภาพ (Quality Control)",
    "brand": "OHAUS",
    "model": "Starter3100C/ ST3100C",
    "serial_number": "B528164053",
    "operation_range": "0-1413 µS/cm",
    "calibration_range": "84 µS/cm\r\n1413 µS/cm",
    "acceptance_criteria": "84±5 , 1413±10 Us/cm",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 45,
    "equipment_id": "BAL-QC-002",
    "equipment_name": "Balance (0.01 g) / (Cap.5,000 g)",
    "owner": "QC",
    "owner_name": "ฝ่ายควบคุมคุณภาพ (Quality Control)",
    "brand": "Njbonitalab",
    "model": "DNC5002",
    "serial_number": "2217300308",
    "operation_range": "0-5000 g",
    "calibration_range": "0-5000 g",
    "acceptance_criteria": "±0.03 g",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "Cal 16/02/24",
    "scheduled_month": "FEB"
  },
  {
    "no": 46,
    "equipment_id": "HTM-QC-001",
    "equipment_name": "Digital Thermo Hygrometer",
    "owner": "QC",
    "owner_name": "ฝ่ายควบคุมคุณภาพ (Quality Control)",
    "brand": "DIGICON",
    "model": "TH-03A",
    "serial_number": "355045870",
    "operation_range": "(-10) - (+50)°C",
    "calibration_range": "25°C,  50 %RH",
    "acceptance_criteria": "±3°C, ±15 %RH",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 47,
    "equipment_id": "HTM-QC-002",
    "equipment_name": "Digital Thermo Hygrometer",
    "owner": "QC",
    "owner_name": "ฝ่ายควบคุมคุณภาพ (Quality Control)",
    "brand": "DIGICON",
    "model": "TH-02A",
    "serial_number": "375013923",
    "operation_range": "(-10) - (+50)°C",
    "calibration_range": "25°C,  50 %RH",
    "acceptance_criteria": "±3°C, ±15 %RH",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 48,
    "equipment_id": "VIS-QC-001",
    "equipment_name": "Viscometer",
    "owner": "QC",
    "owner_name": "ฝ่ายควบคุมคุณภาพ (Quality Control)",
    "brand": "Brookfield",
    "model": "DV2TRVJO",
    "serial_number": "8701186",
    "operation_range": "300-150,000 cps",
    "calibration_range": "800 - 80,000 cps",
    "acceptance_criteria": "+/-3 %",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 49,
    "equipment_id": "LIG-QC-001",
    "equipment_name": "Liquid in glass Thermometer",
    "owner": "QC",
    "owner_name": "ฝ่ายควบคุมคุณภาพ (Quality Control)",
    "brand": "-",
    "model": "-",
    "serial_number": "-",
    "operation_range": "10 - 50°C",
    "calibration_range": "5°C, 10°C,40°C",
    "acceptance_criteria": "±1°C",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 50,
    "equipment_id": "STW-QC-001",
    "equipment_name": "Standard Weight 1 g",
    "owner": "QC",
    "owner_name": "ฝ่ายควบคุมคุณภาพ (Quality Control)",
    "brand": "-",
    "model": "1g",
    "serial_number": "-",
    "operation_range": "1 g",
    "calibration_range": "1 g",
    "acceptance_criteria": "±  1 mg",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 51,
    "equipment_id": "STW-QC-002",
    "equipment_name": "Standard Weight 100 g",
    "owner": "QC",
    "owner_name": "ฝ่ายควบคุมคุณภาพ (Quality Control)",
    "brand": "-",
    "model": "100 g",
    "serial_number": "-",
    "operation_range": "100 g",
    "calibration_range": "100 g",
    "acceptance_criteria": "±  1 mg",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 52,
    "equipment_id": "STW-QC-003",
    "equipment_name": "Standard Weight 100 g",
    "owner": "QC",
    "owner_name": "ฝ่ายควบคุมคุณภาพ (Quality Control)",
    "brand": "-",
    "model": "100 g",
    "serial_number": "-",
    "operation_range": "100 g",
    "calibration_range": "100 g",
    "acceptance_criteria": "±  1 mg",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 53,
    "equipment_id": "STW-QC-004",
    "equipment_name": "Standard Weight 1 Kg",
    "owner": "QC",
    "owner_name": "ฝ่ายควบคุมคุณภาพ (Quality Control)",
    "brand": "-",
    "model": "1 Kg",
    "serial_number": "-",
    "operation_range": "1000g",
    "calibration_range": "1000g",
    "acceptance_criteria": "±  1 g",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 54,
    "equipment_id": "BAL-QC-004",
    "equipment_name": "Balance (0.01 g) / (Cap.5,000 g)",
    "owner": "QC",
    "owner_name": "ฝ่ายควบคุมคุณภาพ (Quality Control)",
    "brand": "TOMS",
    "model": "TM-EXC50002",
    "serial_number": "230401786",
    "operation_range": "0-5000 g",
    "calibration_range": "0-5000 g",
    "acceptance_criteria": "±0.03 g",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 55,
    "equipment_id": "VER-QC-001",
    "equipment_name": "Vernier Caliper",
    "owner": "QC",
    "owner_name": "ฝ่ายควบคุมคุณภาพ (Quality Control)",
    "brand": "MITUTOYO",
    "model": "150 MM",
    "serial_number": "-",
    "operation_range": "0-150 MM",
    "calibration_range": "1 -150 mm",
    "acceptance_criteria": "±0.05 mm",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 56,
    "equipment_id": "STW-QC-005",
    "equipment_name": "Standard Weight 500 g",
    "owner": "MM",
    "owner_name": "คลังวัตถุดิบและบรรจุภัณฑ์ (Warehouse/RM)",
    "brand": "PCH",
    "model": "500g",
    "serial_number": "SS17237",
    "operation_range": "500g",
    "calibration_range": "500g",
    "acceptance_criteria": "±  1 g",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "Cal 19/02/24",
    "scheduled_month": "FEB"
  },
  {
    "no": 57,
    "equipment_id": "BAL-MM-002",
    "equipment_name": "Balance (0.01 kg) / (Cap.150 Kg)",
    "owner": "MM",
    "owner_name": "คลังวัตถุดิบและบรรจุภัณฑ์ (Warehouse/RM)",
    "brand": "OHAUS",
    "model": "T31P",
    "serial_number": "B544630979",
    "operation_range": "0-150 kg",
    "calibration_range": "0-150 kg",
    "acceptance_criteria": "±0.03 kg",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 58,
    "equipment_id": "BAL-MM-004",
    "equipment_name": "Balance (0.01 g) / (Cap.4100g)",
    "owner": "MM",
    "owner_name": "คลังวัตถุดิบและบรรจุภัณฑ์ (Warehouse/RM)",
    "brand": "OHAUS",
    "model": "PA4102",
    "serial_number": "B544655655",
    "operation_range": "0-4100 g",
    "calibration_range": "0-4100 g",
    "acceptance_criteria": "±0.03 g",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 59,
    "equipment_id": "BAL-MM-005",
    "equipment_name": "Balance (0.01 g) / (Cap.4100g)",
    "owner": "MM",
    "owner_name": "คลังวัตถุดิบและบรรจุภัณฑ์ (Warehouse/RM)",
    "brand": "OHAUS",
    "model": "PA4102",
    "serial_number": "B611219724",
    "operation_range": "0-4100 g",
    "calibration_range": "0-4100 g",
    "acceptance_criteria": "±0.03 g",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 60,
    "equipment_id": "BAL-MM-006",
    "equipment_name": "Balance (0.005 Kg) / (Cap.60 Kg)",
    "owner": "MM",
    "owner_name": "คลังวัตถุดิบและบรรจุภัณฑ์ (Warehouse/RM)",
    "brand": "OHAUS",
    "model": "T31P",
    "serial_number": "B544630991",
    "operation_range": "0-60 kg",
    "calibration_range": "0-60 kg",
    "acceptance_criteria": "±0.03 kg",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 61,
    "equipment_id": "BAL-MM-007",
    "equipment_name": "Balance (0.01 g) / ( Cap.5,000 g)",
    "owner": "MM",
    "owner_name": "คลังวัตถุดิบและบรรจุภัณฑ์ (Warehouse/RM)",
    "brand": "Njbonitalab",
    "model": "DNC5002",
    "serial_number": "2217300120",
    "operation_range": "0-5000 g",
    "calibration_range": "0-5000 g",
    "acceptance_criteria": "±0.03 g",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 62,
    "equipment_id": "BAL-MM-008",
    "equipment_name": "Balance (0.01 kg) / (Cap.150 Kg)",
    "owner": "MM",
    "owner_name": "คลังวัตถุดิบและบรรจุภัณฑ์ (Warehouse/RM)",
    "brand": "OHAUS",
    "model": "T31P",
    "serial_number": "B837426421",
    "operation_range": "0-150 kg",
    "calibration_range": "0-150 kg",
    "acceptance_criteria": "±0.03 Kg",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 63,
    "equipment_id": "BAL-MM-009",
    "equipment_name": "Balance (0.002 kg) / (Cap.60 Kg)",
    "owner": "MM",
    "owner_name": "คลังวัตถุดิบและบรรจุภัณฑ์ (Warehouse/RM)",
    "brand": "-",
    "model": "SFL-IN100",
    "serial_number": "20190615042",
    "operation_range": "0-60 kg",
    "calibration_range": "0-60 kg",
    "acceptance_criteria": "±0.03 kg",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 64,
    "equipment_id": "LIG-MM-001",
    "equipment_name": "Liquid in glass Thermometer",
    "owner": "MM",
    "owner_name": "คลังวัตถุดิบและบรรจุภัณฑ์ (Warehouse/RM)",
    "brand": "-",
    "model": "-",
    "serial_number": "-",
    "operation_range": "10 - 50°C",
    "calibration_range": "5°C, 10°C,40°C",
    "acceptance_criteria": "±1°C",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 65,
    "equipment_id": "STW-MM-001",
    "equipment_name": "Standard Weight 20 Kg",
    "owner": "MM",
    "owner_name": "คลังวัตถุดิบและบรรจุภัณฑ์ (Warehouse/RM)",
    "brand": "PCH",
    "model": "20 Kg",
    "serial_number": "C117239",
    "operation_range": "20 Kg",
    "calibration_range": "20 Kg",
    "acceptance_criteria": "± 5 g",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 66,
    "equipment_id": "STW-MM-002",
    "equipment_name": "Standard Weight 20 Kg",
    "owner": "MM",
    "owner_name": "คลังวัตถุดิบและบรรจุภัณฑ์ (Warehouse/RM)",
    "brand": "PCH",
    "model": "20 Kg",
    "serial_number": "C117249",
    "operation_range": "20 Kg",
    "calibration_range": "20 Kg",
    "acceptance_criteria": "± 5 g",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 67,
    "equipment_id": "STW-MM-003",
    "equipment_name": "Standard Weight 20 Kg",
    "owner": "MM",
    "owner_name": "คลังวัตถุดิบและบรรจุภัณฑ์ (Warehouse/RM)",
    "brand": "PCH",
    "model": "20 Kg",
    "serial_number": "C117250",
    "operation_range": "20 Kg",
    "calibration_range": "20 Kg",
    "acceptance_criteria": "± 5 g",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 68,
    "equipment_id": "STW-MM-004",
    "equipment_name": "Standard Weight 20 Kg",
    "owner": "MM",
    "owner_name": "คลังวัตถุดิบและบรรจุภัณฑ์ (Warehouse/RM)",
    "brand": "PCH",
    "model": "20 Kg",
    "serial_number": "C117251",
    "operation_range": "20 Kg",
    "calibration_range": "20 Kg",
    "acceptance_criteria": "± 5 g",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 69,
    "equipment_id": "STW-MM-005",
    "equipment_name": "Standard Weight 20 Kg",
    "owner": "MM",
    "owner_name": "คลังวัตถุดิบและบรรจุภัณฑ์ (Warehouse/RM)",
    "brand": "PCH",
    "model": "20 Kg",
    "serial_number": "C117248",
    "operation_range": "20 Kg",
    "calibration_range": "20 Kg",
    "acceptance_criteria": "± 5 g",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 70,
    "equipment_id": "STW-MM-007",
    "equipment_name": "Standard Weight  2 Kg",
    "owner": "MM",
    "owner_name": "คลังวัตถุดิบและบรรจุภัณฑ์ (Warehouse/RM)",
    "brand": "PCH",
    "model": "2 Kg",
    "serial_number": "-",
    "operation_range": "2 Kg",
    "calibration_range": "2 Kg",
    "acceptance_criteria": "± 1 g",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 71,
    "equipment_id": "HTM-MM-001",
    "equipment_name": "Hygro Thermometer",
    "owner": "MM",
    "owner_name": "คลังวัตถุดิบและบรรจุภัณฑ์ (Warehouse/RM)",
    "brand": "DIGICON",
    "model": "TH-03A",
    "serial_number": "355045869",
    "operation_range": "(-10) - (+50)°C",
    "calibration_range": "25°C,  50 %RH",
    "acceptance_criteria": "±3°C, ±15 %RH",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 72,
    "equipment_id": "HTM-MM-002",
    "equipment_name": "Hygro Thermometer",
    "owner": "MM",
    "owner_name": "คลังวัตถุดิบและบรรจุภัณฑ์ (Warehouse/RM)",
    "brand": "DIGICON",
    "model": "TH-02",
    "serial_number": "355081465",
    "operation_range": "(-10) - (+50)°C",
    "calibration_range": "25°C,  50 %RH",
    "acceptance_criteria": "±3°C, ±15 %RH",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 73,
    "equipment_id": "HTM-MM-003",
    "equipment_name": "Hygro Thermometer",
    "owner": "MM",
    "owner_name": "คลังวัตถุดิบและบรรจุภัณฑ์ (Warehouse/RM)",
    "brand": "DIGICON",
    "model": "TH-02A",
    "serial_number": "375013919",
    "operation_range": "(-10) - (+50)°C",
    "calibration_range": "25°C,  50 %RH",
    "acceptance_criteria": "±3°C, ±15 %RH",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 74,
    "equipment_id": "HTM-MM-006",
    "equipment_name": "Hygro Thermometer",
    "owner": "MM",
    "owner_name": "คลังวัตถุดิบและบรรจุภัณฑ์ (Warehouse/RM)",
    "brand": "DIGICON",
    "model": "TH-02A",
    "serial_number": "385047511",
    "operation_range": "(-10) - (+50)°C",
    "calibration_range": "30°C,  60%RH",
    "acceptance_criteria": "±3°C, ±15 %RH",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 75,
    "equipment_id": "HTM-MM-007",
    "equipment_name": "Hygro Thermometer",
    "owner": "MM",
    "owner_name": "คลังวัตถุดิบและบรรจุภัณฑ์ (Warehouse/RM)",
    "brand": "DIGICON",
    "model": "TH-02A",
    "serial_number": "405003551",
    "operation_range": "(-10) - (+50)°C",
    "calibration_range": "25°C,  50 %RH",
    "acceptance_criteria": "±3°C, ±15 %RH",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "",
    "scheduled_month": "FEB"
  },
  {
    "no": 76,
    "equipment_id": "HTM-MM-008",
    "equipment_name": "Hygro Thermometer",
    "owner": "MM",
    "owner_name": "คลังวัตถุดิบและบรรจุภัณฑ์ (Warehouse/RM)",
    "brand": "DIGICON",
    "model": "TH-02A",
    "serial_number": "425071748",
    "operation_range": "(-10) - (+50)°C",
    "calibration_range": "35°C,  60%RH",
    "acceptance_criteria": "±3°C, ±15 %RH",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "เพิ่มเติม 25/03/24",
    "scheduled_month": "MAR"
  },
  {
    "no": 77,
    "equipment_id": "HTM-MM-009",
    "equipment_name": "Hygro Thermometer",
    "owner": "MM",
    "owner_name": "คลังวัตถุดิบและบรรจุภัณฑ์ (Warehouse/RM)",
    "brand": "DIGICON",
    "model": "TH-02A",
    "serial_number": "425071746",
    "operation_range": "(-10) - (+50)°C",
    "calibration_range": "35°C,  60%RH",
    "acceptance_criteria": "±3°C, ±15 %RH",
    "interval_months": 12,
    "cal_type": "External",
    "cal_provider": "สถาบัน/ห้องปฏิบัติการภายนอก (External Lab)",
    "status_note": "เพิ่มเติม 25/03/24",
    "scheduled_month": "MAR"
  }
]
