import { Company, Contact, PipelineStage, Deal, ActivityLog } from './types'

export const DEFAULT_STAGES: PipelineStage[] = [
  {
    id: 'stage-1-lead',
    name: '1. ลีดใหม่ / สนใจผลิต (New Lead)',
    description: 'ลูกค้าทักแชท สอบถามข้อมูลเบื้องต้น ได้เบอร์ติดต่อ',
    probability: 10,
    color: 'bg-slate-100 text-slate-800 border-slate-300',
    order: 1,
    rottingDays: 3,
  },
  {
    id: 'stage-2-brief',
    name: '2. รับบรีฟสเปก & ประเมิน (Brief & Feasibility)',
    description: 'คุยประเภทสินค้า เนื้อสัมผัส สารสกัด งบประมาณ และจำนวนผลิต',
    probability: 25,
    color: 'bg-blue-50 text-blue-800 border-blue-200',
    order: 2,
    rottingDays: 5,
  },
  {
    id: 'stage-3-sample',
    name: '3. วิจัยสูตร & ส่งตัวอย่าง (R&D Sample Dev)',
    description: 'ทีม R&D พัฒนาสูตร และจัดส่ง Tester ให้ลูกค้าทดลอง',
    probability: 40,
    color: 'bg-purple-50 text-purple-800 border-purple-200',
    order: 3,
    rottingDays: 10,
  },
  {
    id: 'stage-4-approved',
    name: '4. ปรับแก้ & สรุปสูตร (Formula Approved)',
    description: 'ลูกค้าทดสอบเนื้อและกลิ่นเรียบร้อย เซ็นอนุมัติสูตรมาตรฐาน',
    probability: 60,
    color: 'bg-amber-50 text-amber-800 border-amber-200',
    order: 4,
    rottingDays: 7,
  },
  {
    id: 'stage-5-quotation',
    name: '5. เสนอราคา & แพ็กเกจจิ้ง (Quotation & Packaging)',
    description: 'สรุปราคาต่อชิ้น ขนาดบรรจุภัณฑ์ และส่งใบเสนอราคา (Quotation)',
    probability: 75,
    color: 'bg-orange-50 text-orange-800 border-orange-200',
    order: 5,
    rottingDays: 7,
  },
  {
    id: 'stage-6-contract-fda',
    name: '6. มัดจำ & ยื่น อย. (Contract, Deposit & FDA)',
    description: 'ลูกค้าชำระมัดจำ 50% ทำสัญญา และยื่นขอเลขจดแจ้ง อย.',
    probability: 90,
    color: 'bg-indigo-50 text-indigo-800 border-indigo-200',
    order: 6,
    rottingDays: 14,
  },
  {
    id: 'stage-7-won',
    name: '7. ปิดการขายสำเร็จ (Closed Won - ส่งผลิต)',
    description: 'เอกสารครบ มัดจำเข้า ส่งคิวเข้าฝ่ายวางแผนผลิต (Planning)',
    probability: 100,
    color: 'bg-emerald-50 text-emerald-800 border-emerald-300',
    order: 7,
    isWon: true,
  },
  {
    id: 'stage-8-lost',
    name: '8. ไม่สำเร็จ (Closed Lost)',
    description: 'ปิดการขายไม่สำเร็จ พร้อมบันทึกเหตุผลวิเคราะห์',
    probability: 0,
    color: 'bg-rose-50 text-rose-800 border-rose-200',
    order: 8,
    isLost: true,
  },
]

export const SALES_REPS = [
  'วรรณิศา (กิ๊ก)',
  'ธนกฤต (มาร์ค)',
  'พิชญา (แพร)',
  'ณัฐพล (อาร์ม)',
  'กัญญารัตน์ (วิว)',
]

export const INITIAL_COMPANIES: Company[] = [
  {
    id: 'comp-1',
    name: 'บริษัท สยามคอสเมติก กรุ๊ป จำกัด',
    brandName: 'GLOW-ON Skincare',
    taxId: '0105558123451',
    tier: 'TIER_1',
    channelDescription: 'ห้างสรรพสินค้า / EVEANDBOY / BEAUTRIUM / TikTok Official Shop',
    phone: '02-888-9999',
    email: 'contact@glowon-skin.com',
    createdAt: '2026-06-15',
  },
  {
    id: 'comp-2',
    name: 'บริษัท ออร่าไวท์ คอร์ปอเรชั่น จำกัด',
    brandName: 'Aura Aura White',
    taxId: '0105561098765',
    tier: 'TIER_1',
    channelDescription: 'TikTok Creator Top 3 / Shopee Mall / Lazada',
    phone: '081-444-5555',
    email: 'aurawhite@gmail.com',
    createdAt: '2026-07-01',
  },
  {
    id: 'comp-3',
    name: 'บริษัท บิวตี้อินสไปร์ แลบส์ จำกัด',
    brandName: 'DermaPure Clinical',
    taxId: '0105559332211',
    tier: 'TIER_1',
    channelDescription: 'Watsons 200 สาขา / ร้านขายยาชั้นนำ',
    phone: '02-777-1122',
    email: 'dermapure.th@gmail.com',
    createdAt: '2026-07-20',
  },
  {
    id: 'comp-4',
    name: 'ดีกา คลินิกเวชกรรม (Dheka Aesthetic Clinic)',
    brandName: 'Dr. Dheka Formulas',
    taxId: '0105562011223',
    tier: 'TIER_2',
    channelDescription: 'คลินิกความงาม 4 สาขา (สยาม, ทองหล่อ, ปิ่นเกล้า, เชียงใหม่)',
    phone: '089-999-1234',
    email: 'purchase@dhekaclinic.com',
    createdAt: '2026-08-01',
  },
  {
    id: 'comp-5',
    name: 'สลิมมิ่ง พลัส สปา แอนด์ เวลเนส (Slimming Plus Spa)',
    brandName: 'Aroma Sanctuary Spa',
    tier: 'TIER_2',
    channelDescription: 'พรีเมียมเดย์สปา โรงแรม 5 ดาว และช็อปออนไลน์',
    phone: '086-555-8899',
    email: 'sanctuary.spa@gmail.com',
    createdAt: '2026-08-10',
  },
  {
    id: 'comp-6',
    name: 'คุณพิมพ์มาดา สตาร์ทอัพแบรนด์ใหม่',
    brandName: 'RootRise Hair Tonic',
    tier: 'TIER_2',
    channelDescription: 'SME ผู้ประกอบการใหม่ ยิงแอด Facebook / LINE Shopping',
    phone: '092-333-7711',
    email: 'pimrada.hair@outlook.com',
    createdAt: '2026-08-25',
  },
  {
    id: 'comp-7',
    name: 'เดอร์มาแล็บ สตูดิโอ (DermaLab Studio)',
    brandName: 'Clear Acne Solution',
    tier: 'TIER_2',
    channelDescription: 'แพทย์ผิวหนัง จำหน่ายหน้าร้านและ TikTok Shop',
    phone: '083-111-2244',
    email: 'dermalab.studio@gmail.com',
    createdAt: '2026-09-02',
  },
]

export const INITIAL_CONTACTS: Contact[] = [
  {
    id: 'cont-1',
    companyId: 'comp-1',
    name: 'คุณกิตติศักดิ์ อัศวเดช',
    role: 'Managing Director / เจ้าของแบรนด์',
    phone: '081-888-9999',
    lineId: '@glowon_ceo',
    email: 'kittisak@glowon-skin.com',
    isPrimary: true,
    createdAt: '2026-06-15',
  },
  {
    id: 'cont-2',
    companyId: 'comp-2',
    name: 'คุณพิมพ์พิชชา วรนันท์',
    role: 'Head of Product & Influencer Partner',
    phone: '081-444-5555',
    lineId: 'pimpitcha_aura',
    email: 'pimpitcha@aurawhite.com',
    isPrimary: true,
    createdAt: '2026-07-01',
  },
  {
    id: 'cont-3',
    companyId: 'comp-3',
    name: 'เภสัชกรหญิง ชลธิชา เลิศปรีชา',
    role: 'ผู้จัดการฝ่ายจัดซื้อและพัฒนาผลิตภัณฑ์',
    phone: '089-777-1122',
    lineId: 'chonticha_derm',
    email: 'chonticha@dermapure.com',
    isPrimary: true,
    createdAt: '2026-07-20',
  },
  {
    id: 'cont-4',
    companyId: 'comp-4',
    name: 'นพ. ธีรภัทร ปัญญากุล',
    role: 'ผู้อำนวยการแพทย์ & ผู้ก่อตั้งคลินิก',
    phone: '089-999-1234',
    lineId: 'dr.theerapat',
    email: 'dr.theerapat@dhekaclinic.com',
    isPrimary: true,
    createdAt: '2026-08-01',
  },
  {
    id: 'cont-5',
    companyId: 'comp-5',
    name: 'คุณศศิธร มงคลสุข',
    role: 'ผู้จัดการฝ่ายปฏิบัติการสปา',
    phone: '086-555-8899',
    lineId: 'sasithorn_spa',
    email: 'sasithorn.spa@gmail.com',
    isPrimary: true,
    createdAt: '2026-08-10',
  },
  {
    id: 'cont-6',
    companyId: 'comp-6',
    name: 'คุณพิมพ์มาดา ภิรมย์รักษ์',
    role: 'Founder & CEO',
    phone: '092-333-7711',
    lineId: 'pim_rootrise',
    email: 'pimrada.hair@outlook.com',
    isPrimary: true,
    createdAt: '2026-08-25',
  },
  {
    id: 'cont-7',
    companyId: 'comp-7',
    name: 'พญ. พัชรพร อัครเดชา',
    role: 'แพทย์ผิวหนังเฉพาะทาง',
    phone: '083-111-2244',
    lineId: 'dr.patcharaporn',
    email: 'dermalab.studio@gmail.com',
    isPrimary: true,
    createdAt: '2026-09-02',
  },
]

export const INITIAL_DEALS: Deal[] = [
  {
    id: 'deal-101',
    code: 'DL-2609-001',
    title: 'GLOW-ON ไวท์เทนนิ่งครีมเข้มข้น ล็อตใหญ่เข้าห้าง',
    companyId: 'comp-1',
    contactId: 'cont-1',
    salesRep: 'วรรณิศา (กิ๊ก)',
    stageId: 'stage-7-won',
    dealValue: 3850000,
    quantity: 50000,
    productCategory: 'skincare',
    formulaType: 'ODM',
    packagingStatus: 'CONFIRMED',
    fdaStatus: 'APPROVED',
    sampleStatus: 'APPROVED',
    expectedCloseDate: '2026-09-12',
    nextActionDate: '2026-09-18',
    nextActionNote: 'ตรวจทานใบส่งต่องาน Planning คิวผสมถัง 300KG',
    checklist: [
      { id: 'c1', label: 'วิจัยและทดสอบความคงตัวสูตรผ่าน', completed: true, completedAt: '2026-08-20' },
      { id: 'c2', label: 'สรุปขนาดขวดและกล่องลงลัง', completed: true, completedAt: '2026-08-25' },
      { id: 'c3', label: 'ยื่นจดแจ้ง อย. สำเร็จ มีเลข 10-1-xxxx', completed: true, completedAt: '2026-09-05' },
      { id: 'c4', label: 'รับชำระเงินมัดจำงวดแรก 50% (1,925,000 บาท)', completed: true, completedAt: '2026-09-12' },
    ],
    createdAt: '2026-08-10',
    updatedAt: '2026-09-12',
    lastActivityDate: '2026-09-15',
  },
  {
    id: 'deal-102',
    code: 'DL-2609-002',
    title: 'Aura Aura ครีมกันแดดเนื้อน้ำ บางเบา คุมมัน (TikTok Big Lot)',
    companyId: 'comp-2',
    contactId: 'cont-2',
    salesRep: 'ธนกฤต (มาร์ค)',
    stageId: 'stage-6-contract-fda',
    dealValue: 2450000,
    quantity: 35000,
    productCategory: 'sunscreen',
    formulaType: 'ODM',
    packagingStatus: 'CONFIRMED',
    fdaStatus: 'SUBMITTED',
    sampleStatus: 'APPROVED',
    expectedCloseDate: '2026-09-25',
    nextActionDate: '2026-09-18',
    nextActionNote: 'ติดตามเอกสารสัญญาและสลิปมัดจำ 50% จากฝ่ายบัญชีลูกค้า',
    checklist: [
      { id: 'c1', label: 'ส่งตัวอย่าง SPF50+ PA++++ ลูกค้าอนุมัติ', completed: true, completedAt: '2026-09-02' },
      { id: 'c2', label: 'เลือกหลอดซอฟต์ทัชฝาปั๊มเรียบร้อย', completed: true, completedAt: '2026-09-08' },
      { id: 'c3', label: 'ยื่นจดแจ้ง อย. วันที่ 10 ก.ย. รออนุมัติ', completed: true, completedAt: '2026-09-10' },
      { id: 'c4', label: 'รอเงินมัดจำงวดที่ 1', completed: false },
    ],
    createdAt: '2026-08-18',
    updatedAt: '2026-09-16',
    lastActivityDate: '2026-09-16',
  },
  {
    id: 'deal-103',
    code: 'DL-2609-003',
    title: 'DermaPure เซรั่มลดริ้วรอยเปปไทด์เข้มข้น กระจาย 200 สาขา',
    companyId: 'comp-3',
    contactId: 'cont-3',
    salesRep: 'พิชญา (แพร)',
    stageId: 'stage-5-quotation',
    dealValue: 1980000,
    quantity: 20000,
    productCategory: 'facial_care',
    formulaType: 'OEM',
    packagingStatus: 'SAMPLE_REVIEW',
    fdaStatus: 'FACTORY_REG',
    sampleStatus: 'APPROVED',
    expectedCloseDate: '2026-09-30',
    nextActionDate: '2026-09-19',
    nextActionNote: 'ส่งใบเสนอราคาฉบับแก้ไข ส่วนลด MOQ 20,000 ชิ้น',
    checklist: [
      { id: 'c1', label: 'ทดสอบสูตรเปปไทด์ตามสเปกของลูกค้า', completed: true, completedAt: '2026-09-05' },
      { id: 'c2', label: 'เสนอแบบขวดดรอปเปอร์แก้วชา', completed: true, completedAt: '2026-09-12' },
      { id: 'c3', label: 'ส่ง Quotation และตาราง Lead Time ผลิต', completed: false },
    ],
    createdAt: '2026-08-22',
    updatedAt: '2026-09-15',
    lastActivityDate: '2026-09-15',
  },
  {
    id: 'deal-104',
    code: 'DL-2609-004',
    title: 'Dr. Dheka เซรั่มฟื้นฟูผิวหลังเลเซอร์สูตรเฉพาะแพทย์',
    companyId: 'comp-4',
    contactId: 'cont-4',
    salesRep: 'ณัฐพล (อาร์ม)',
    stageId: 'stage-4-approved',
    dealValue: 450000,
    quantity: 3000,
    productCategory: 'facial_care',
    formulaType: 'ODM',
    packagingStatus: 'SOURCING',
    fdaStatus: 'NOT_STARTED',
    sampleStatus: 'APPROVED',
    expectedCloseDate: '2026-10-05',
    nextActionDate: '2026-09-20',
    nextActionNote: 'คุณหมอคอนเฟิร์มสูตรแล็บรอบที่ 2 แล้ว เตรียมนัดคุยขนาดขวดและราคา',
    checklist: [
      { id: 'c1', label: 'ส่งตัวอย่างสูตร Cica + Ceramide', completed: true, completedAt: '2026-08-30' },
      { id: 'c2', label: 'ปรับลดความเหนียวและส่งตัวอย่างรอบ 2', completed: true, completedAt: '2026-09-10' },
      { id: 'c3', label: 'คุณหมอทดลองในคลินิกผ่านเกณฑ์ สรุป Approved', completed: true, completedAt: '2026-09-14' },
      { id: 'c4', label: 'ทำใบเสนอราคา 3,000 ชิ้น', completed: false },
    ],
    createdAt: '2026-08-28',
    updatedAt: '2026-09-14',
    lastActivityDate: '2026-09-14',
  },
  {
    id: 'deal-105',
    code: 'DL-2609-005',
    title: 'Slimming Plus สครับเกลือหิมาลายันน้ำนมข้าว สปาระดับโรงแรม',
    companyId: 'comp-5',
    contactId: 'cont-5',
    salesRep: 'กัญญารัตน์ (วิว)',
    stageId: 'stage-3-sample',
    dealValue: 320000,
    quantity: 2000,
    productCategory: 'body_care',
    formulaType: 'ODM',
    packagingStatus: 'SOURCING',
    fdaStatus: 'NOT_STARTED',
    sampleStatus: 'LAB_DEVELOPING',
    expectedCloseDate: '2026-10-15',
    nextActionDate: '2026-09-21',
    nextActionNote: 'ห้องแล็บ R&D ส่งตัวอย่าง 2 กลิ่น (กระดังงา & ข้าวหอมมะลิ)',
    checklist: [
      { id: 'c1', label: 'รับบรีฟขนาดเม็ดสครับและกลิ่นอโรมา', completed: true, completedAt: '2026-09-06' },
      { id: 'c2', label: 'R&D ผสมตัวอย่างในห้องแล็บ', completed: false },
      { id: 'c3', label: 'ส่ง Tester ให้ทีมสปาทดลอง', completed: false },
    ],
    createdAt: '2026-09-05',
    updatedAt: '2026-09-12',
    lastActivityDate: '2026-09-12',
  },
  {
    id: 'deal-106',
    code: 'DL-2609-006',
    title: 'RootRise โทนิกบำรุงรากผมสารสกัดใบหมี่และขิงดำ',
    companyId: 'comp-6',
    contactId: 'cont-6',
    salesRep: 'วรรณิศา (กิ๊ก)',
    stageId: 'stage-2-brief',
    dealValue: 185000,
    quantity: 1000,
    productCategory: 'haircare',
    formulaType: 'ODM',
    packagingStatus: 'SOURCING',
    fdaStatus: 'NOT_STARTED',
    sampleStatus: 'PENDING_BRIEF',
    expectedCloseDate: '2026-10-20',
    nextActionDate: '2026-09-19',
    nextActionNote: 'โทรสรุปงบประมาณต่อชิ้นและส่งเอกสารสารสกัดเด่นให้ลูกค้าเลือก',
    checklist: [
      { id: 'c1', label: 'ทักมาจาก LINE แอดมินส่งต่อให้เซลล์', completed: true, completedAt: '2026-09-10' },
      { id: 'c2', label: 'โทรคุยบรีฟรอบแรก งบเริ่มต้น 2 แสนบาท', completed: true, completedAt: '2026-09-12' },
      { id: 'c3', label: 'ส่งฟอร์มบรีฟ R&D พัฒนาสูตรตัวอย่าง', completed: false },
    ],
    createdAt: '2026-09-10',
    updatedAt: '2026-09-12',
    lastActivityDate: '2026-09-12',
  },
  {
    id: 'deal-107',
    code: 'DL-2609-007',
    title: 'Clear Acne เจลแต้มสิวสูตรเร่งด่วน 24 ชม.',
    companyId: 'comp-7',
    contactId: 'cont-7',
    salesRep: 'ธนกฤต (มาร์ค)',
    stageId: 'stage-1-lead',
    dealValue: 280000,
    quantity: 2500,
    productCategory: 'facial_care',
    formulaType: 'OEM',
    packagingStatus: 'CLIENT_SUPPLIED',
    fdaStatus: 'FACTORY_REG',
    sampleStatus: 'PENDING_BRIEF',
    expectedCloseDate: '2026-10-30',
    nextActionDate: '2026-09-18',
    nextActionNote: 'ขอรายละเอียดสูตรเดิมของคลินิกเพื่อส่งฝ่าย QA/R&D ตรวจสอบความเข้ากันได้',
    checklist: [
      { id: 'c1', label: 'ลูกค้าทัก Inbox Facebook ขอผลิตสูตรเดิม', completed: true, completedAt: '2026-09-15' },
      { id: 'c2', label: 'นัดคุยโทรศัพท์บ่ายวันพรุ่งนี้', completed: false },
    ],
    createdAt: '2026-09-15',
    updatedAt: '2026-09-16',
    lastActivityDate: '2026-09-16',
  },
  {
    id: 'deal-108',
    code: 'DL-2609-008',
    title: 'สบู่เหลวอาบน้ำกลิ่นกุหลาบออร์แกนิก ล็อตทดลองตลาด',
    companyId: 'comp-5',
    contactId: 'cont-5',
    salesRep: 'พิชญา (แพร)',
    stageId: 'stage-8-lost',
    dealValue: 120000,
    quantity: 500,
    productCategory: 'personal_care',
    formulaType: 'OEM',
    packagingStatus: 'SOURCING',
    fdaStatus: 'NOT_STARTED',
    sampleStatus: 'PENDING_BRIEF',
    expectedCloseDate: '2026-09-10',
    lossReason: 'MOQ ขั้นต่ำไม่ตรงกับแผนงบประมาณ',
    lossNote: 'ลูกค้าต้องการสั่งเพียง 200 ชิ้น แต่โรงงานขั้นต่ำผสมถัง 300KG (ได้ ~500-600 ขวด) จึงยังไม่พร้อมเปิดออเดอร์',
    checklist: [
      { id: 'c1', label: 'แจ้งเงื่อนไขขนาดถังผสม 300KG', completed: true, completedAt: '2026-09-08' },
    ],
    createdAt: '2026-09-01',
    updatedAt: '2026-09-10',
    lastActivityDate: '2026-09-10',
  },
]

export const INITIAL_ACTIVITIES: ActivityLog[] = [
  {
    id: 'act-1',
    dealId: 'deal-101',
    type: 'STAGE_CHANGE',
    title: 'ย้ายดีลสู่สถานะ ปิดการขายสำเร็จ (Closed Won)',
    description: 'เงินมัดจำ 50% เข้าบัญชีเรียบร้อย ส่งเอกสารให้ฝ่ายวางแผนผลิตและจัดซื้อ RM/PM',
    actor: 'วรรณิศา (กิ๊ก)',
    createdAt: '2026-09-12 14:30',
  },
  {
    id: 'act-2',
    dealId: 'deal-102',
    type: 'LINE',
    title: 'แชทสรุปสีฝาปั๊มและฟอยล์พิมพ์กล่อง',
    description: 'ลูกค้าคอนเฟิร์ม Hot Stamping สีทองด้าน ตรงตาม Proof',
    actor: 'ธนกฤต (มาร์ค)',
    createdAt: '2026-09-16 11:20',
  },
  {
    id: 'act-3',
    dealId: 'deal-103',
    type: 'CALL',
    title: 'โทรชี้แจงส่วนลดขั้นบันได 10,000 vs 20,000 ชิ้น',
    description: 'แจ้งเภสัชกรชลธิชาว่าหากเปิด 20,000 ชิ้น จะประหยัดต้นทุนชั่งผสมและบรรจุได้ชิ้นละ 4.5 บาท',
    actor: 'พิชญา (แพร)',
    createdAt: '2026-09-15 16:45',
  },
  {
    id: 'act-4',
    dealId: 'deal-104',
    type: 'SAMPLE',
    title: 'ส่งผลทดสอบแล็บรอบที่ 2',
    description: 'ผลทดสอบความหนืด 4,200 cPs และ pH 5.5 เหมาะกับผิวแพ้ง่าย',
    actor: 'ณัฐพล (อาร์ม)',
    createdAt: '2026-09-14 10:15',
  },
]
